### ISSUE TITLE
TypeScript backwards compatibility not given

### ISSUE THREAD

**Issue by DavidTalamona** [mpalourdio/intl-tel-input-ng#10]
## Actual behavior
When using "intl-tel-input-ng" with Ionic 4, which is forcing TypeScript 4.3.4 (and Angular 8.1.2) I get the following error:
`An accessor cannot be declared in an ambient context.`

I understood that I would have to update TypeScript to 3.7+ but as I sad, Ionic 4 does not let me (forces TS < 3.5).
Is it possible to change the code in a way, so that it's backwards compatible?

## intl-tel-input-ng version
0.1.0
Works fine with 0.7.0

**Comment by mpalourdio** [comment]
Sorry, but that won't happen. Upgrading typescript is cheap. The ionic team should follow the `angular` peer dependencies.
