### ISSUE TITLE
ReactiveFormsModule support

### ISSUE THREAD

**Issue by pasevin** [mpalourdio/intl-tel-input-ng#2]
Would be awesome to support ReactiveFormsModule.
Otherwise great adaptation!

**Comment by mpalourdio** [comment]
Thanks for feedback, I do not use myself ReactiveFormsModule as my needs are very light. Could you please point me in which way this is not compliant with `ReactiveFormsModule` at the moment ?

**Comment by mpalourdio** [comment]
Oh I see. In fact, this module was made for ma particular use case at first. And I wanted something easy to integrate for template driven forms. The quick fix could maybe be something like this (ie, move the `formGroup` on a chlid node : 

```xml
<form #f="ngForm">
   <div [formGroup]="checkoutForm">
       <intl-tel-input
           [label]="'Please enter your phone number'"
           [name]="'my-name'"
           [cssClass]="'form-control'"
           [required]="true"
           [options]="{
               preferredCountries: ['us', 'gb']
           }"
           [(E164PhoneNumber)]="E164PhoneNumber"></intl-tel-input>
    </div>
</form>     
```

As I have never used `ReactiveForms`, not sure if really does the trick. Please let me know

**Comment by pasevin** [comment]
Thanks, I haven't thought about adding another div :]
It's not crashing anymore ;)
