### ISSUE TITLE
Can't erase phone number with formatOnDisplay = true

### ISSUE THREAD

**Issue by s-o-f** [mpalourdio/intl-tel-input-ng#23]
## Actual behavior
Can't erase phone number

## Steps to reproduce
Enter phone number: +79111188888 (can be copy-pasted)
Try to erase last digit (press backspace)
![out](https://user-images.githubusercontent.com/3519997/130213617-aa933685-def6-46a5-960f-c46e7e8b8b9f.gif)

## intl-tel-input-ng version
0.4.0

**Comment by mpalourdio** [comment]
Thanks for this clear bug report, kudos! Looks like the bug is not here, but in the main library.
I have tried here : https://accounts.intuit.com/signup.html, and the same bug appears, whereas they do not use my integration for angular.

You should report the bug in the main repo [here](https://github.com/jackocnr/intl-tel-input/issues) instead.

Thanks.

**Comment by s-o-f** [comment]
>  Looks like the bug is not here, but in the main library.

I don't think so.
I can't reproduce this on official demo page https://intl-tel-input.com/

Looks like here https://accounts.intuit.com/signup.html they are using something like [these hack](https://github.com/jackocnr/intl-tel-input/issues/346#issuecomment-595404009) that leads to the bug.

I found temporary solution for your component. It works, but not tested carefully.
Remove these:
```
if (!!value) {
      this._intlTelInput.setNumber(value);
    }
```

Add these:
```
keyUp() {
    if (this._intlTelInput.isValidNumber()) {
      this._intlTelInput.setNumber(this._intlTelInput.getNumber());
    }
  }
```

And add input attributes:
```
(keyup)="keyUp($event)"
(change)="keyUp($event)"
```

**Comment by mpalourdio** [comment]
Yes it is. The bug is caused by the auto-format feature in the lib, which the demo page does not use. That waht [this thread](https://github.com/jackocnr/intl-tel-input/issues/346#issuecomment-595404009) is all about.
