### ISSUE TITLE
Display existing number

### ISSUE THREAD

**Issue by edizsuleyman** [mpalourdio/intl-tel-input-ng#3]
I was looking a way to display my already existing phone number on input, but I couldn't find anything related to that. I found something in **intl-tel-input**, but it was with jquery and  I didn't know how can I implement it on angular.
So I want to have something like this:
**`<intl-tel-input  [(ngModel)]="myExistingNumber" id="phone"></intl-tel-input>`**

Is there a way I can display it? 
I really need help with it.

**Comment by mpalourdio** [comment]
There's no easy way at the moment. You can do something like this :

```typescript
export class MyComponent implements  AfterViewInit {
    @ViewChild(IntlTelInputComponent) public intlTelinputComponent;

    public ngAfterViewInit(): void {
        setTimeout(() => {
            this.intlTelinputComponent.phoneNumber = '+33677889955';
        });
    }
}
```

**Comment by edizsuleyman** [comment]
@mpalourdio thanks mate, this worked perfectly!
You are a life saver :)

**Comment by edizsuleyman** [comment]
@mpalourdio I need one more help with geoIp. I don't know how to use it as syntax, or maybe it is not working because I am on localhost.

```
<intl-tel-input  #intlPhones id="phoneNo" [cssClass]="'form-control details-input-payment'" 
       [options]="{
             preferredCountries: ['ch', 'xk'],
             separateDialCode: 'true',
             initialCountry: 'auto',
             geoIpLookup: { callback: { 'countryCode': 'us'}}
        }">
</intl-tel-input>
```

What I am trying to do is, I want that country to be set according to my geolocation. If not found any, add 'US' by default. I am not sure if the syntax is correct. I don't get any errors though, maybe it doesn't work in localhost. 

I would appreciate help for this.
Regards.

**Comment by mpalourdio** [comment]
You obviously need an IP geolocation service provider.
